language: python
python:
    - "nightly"
    #- "pypy"
    - "3.5-dev"
    - "3.5"
    - "3.4"
    #- "3.3" # NOTE disabled due to incompatibility with inspect.signature
install: "pip install kotoba && pip install ."
script:  "python -m unittest discover -s test/v2"
